### ISSUE TITLE
Rarible Protocol Starter App

### ISSUE THREAD

**Issue by bertux** [fuse-guild/scaffold-fuse#1]
- https://docs.rarible.org/starter-app
- https://github.com/austintgriffith/scaffold-eth/tree/rarible-starter-app

**Comment by JanOwiesniak** [comment]
**#1 Session**

Deployed on Ropsten Network

**Comment by bertux** [comment]
https://ropsten.rarible.com/token/0xaed6CC6936D2C659719Aef48D791A85Fc88d2e14:1?tab=owners

**Comment by JanOwiesniak** [comment]
#2 Session (Next)

Deploy on FUSE Network

**Comment by bertux** [comment]
History of Rarible usage: https://ropsten.rarible.com/token/0xaed6CC6936D2C659719Aef48D791A85Fc88d2e14:1?tab=history
